# Generated by Django 2.2.6 on 2019-11-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0003_auto_20191117_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.FilePathField(default=False, path='static/img'),
        ),
    ]
